http:

#region routers 
  routers:

    hlpve1:
      entryPoints:
        - https
      rule: "Host(`pve1.hl.adeotek.cloud`)"
      middlewares:
        - default-headers
        - https-redirectscheme
      tls: {}
      service: hlpve1

    hlnas1:
      entryPoints:
        - https
      rule: "Host(`nas.hl.adeotek.cloud`)"
      middlewares:
        - default-headers
        - https-redirectscheme
      tls: {}
      service: hlnas1

    piholepr:
      entryPoints:
        - https
      rule: "Host(`pi-hole.hl.adeotek.cloud`)"
      middlewares:
        - default-headers
        - https-redirectscheme
      tls: {}
      service: piholepr

    piholedr:
      entryPoints:
        - https
      rule: "Host(`pi-hole-dr.hl.adeotek.cloud`)"
      middlewares:
        - default-headers
        - https-redirectscheme
      tls: {}
      service: piholedr
  
#endregion

#region services
  services:

    hlpve1:
      loadBalancer:
        servers:
          - url: "https://192.168.189.21:8006"
        passHostHeader: true

    hlnas1:
      loadBalancer:
        servers:
          - url: "http://192.168.189.20:80"
        passHostHeader: true

    piholepr:
      loadBalancer:
        servers:
          - url: "https://192.168.189.51:443"
        passHostHeader: true

    piholedr:
      loadBalancer:
        servers:
          - url: "https://192.168.189.52:443"
        passHostHeader: true

#endregion

  middlewares:
    https-redirectscheme:
      redirectScheme:
        scheme: https
        permanent: true
    default-headers:
      headers:
        frameDeny: true
        browserXssFilter: true
        contentTypeNosniff: true
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsPreload: true
        stsSeconds: 15552000
        customFrameOptionsValue: SAMEORIGIN
        customRequestHeaders:
          X-Forwarded-Proto: https

    default-whitelist:
      ipAllowList:
        sourceRange:
        - "10.0.0.0/8"
        - "192.168.0.0/16"
        - "172.16.0.0/12"

    secured:
      chain:
        middlewares:
        - default-whitelist
        - default-headers
