################################################################
#
# Configuration sample for Traefik v2.
#
################################################################

################################################################
# Global configuration
################################################################
global:
  checkNewVersion: true
  sendAnonymousUsage: false

serversTransport:
  insecureSkipVerify: true

################################################################
# EntryPoints configuration
################################################################
entryPoints:
  http:
    address: :80
    http:
      redirections:
        entryPoint:
          to: https
          scheme: https
  https:
    address: :443

################################################################
# Docker configuration backend
################################################################
providers:
  docker:
    endpoint: unix:///var/run/docker.sock
    exposedByDefault: false
#    defaultRule: Host(`{{ normalize .Name }}.hl.adeotek.cloud`)
  file:
    filename: /etc/traefik/proxy.yml

################################################################
# Certificates Resolvers
################################################################
certificatesResolvers:
  cloudflare:
    acme:
      email: george.benjamin@gmail.com
      storage: acme.json
      # caServer: https://acme-v02.api.letsencrypt.org/directory # prod (default)
      caServer: https://acme-staging-v02.api.letsencrypt.org/directory # staging
      dnsChallenge:
        provider: cloudflare
        #disablePropagationCheck: true # uncomment this if you have issues pulling certificates through cloudflare, By setting this flag to true disables the need to wait for the propagation of the TXT record to all authoritative name servers.
        #delayBeforeCheck: 60s # uncomment along with disablePropagationCheck if needed to ensure the TXT record is ready before verification is attempted 
        resolvers:
          - "1.1.1.1:53"
          - "1.0.0.1:53"

################################################################
# API and dashboard configuration
################################################################
api:
  dashboard: true
  debug: true # ???
#  insecure: true # Default: false

################################################################
# Traefik logs configuration
################################################################
log:
  level: DEBUG # Default: "ERROR"
  filePath: /var/log/traefik/traefik.log
#  format: json # Default: "common"

################################################################
# Access logs configuration
################################################################
accessLog:
  filePath: /var/log/traefik/access.log
#  format: json # Default: "common"

################################################################
# Ping configuration
################################################################
#ping:
#  entryPoint: traefik # Default: "traefik"
