---
services:

  gotify:
    image: gotify/server:latest
    container_name: com--gotify
    restart: unless-stopped
    ports:
      - 8180:80
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config/config.yml:/etc/gotify/config.yml
      - ./data/:/app/data/
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gotify.rule=Host(`signals.adeotek.cloud`)"
      - "traefik.http.routers.gotify.entrypoints=https-external"
      # - "traefik.http.routers.gotify.rule=Host(`signals.hl.adeotek.cloud`)"
      # - "traefik.http.routers.gotify.entrypoints=https"
      - "traefik.http.routers.gotify.tls=true"
      - "traefik.http.services.gotify.loadbalancer.server.port=80"

networks:
  proxy:
    external: true
