---
services:

  gotify:
    image: gotify/server:latest
    container_name: gotify
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config/config.yml:/etc/gotify/config.yml
      - ./data:/app/data
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gotify.rule=Host(`signals.example.com`)"
      - "traefik.http.routers.gotify.entrypoints=https-external"
      - "traefik.http.routers.gotify.tls=true"
      - "traefik.http.services.gotify.loadbalancer.server.port=80"

networks:
  proxy:
    name: proxy
    external: true
