---
services:

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    restart: unless-stopped
    ports:
      - 8080:8080
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - open-webui-data:/home/node/.n8n
    environment:
      - OLLAMA_BASE_URL=http://ollama.lan:11434
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=sys--proxy"
      - "traefik.http.routers.open-webui.rule=Host(`ai.example.com`)"
      - "traefik.http.routers.open-webui.entrypoints=https"
      - "traefik.http.routers.open-webui.tls=true"
      - "traefik.http.routers.open-webui.middlewares=internal-whitelist@file"
      - "traefik.http.services.open-webui.loadbalancer.server.port=8080"

volumes:
  open-webui-data:
    driver: local

networks:
  proxy:
    name: sys--proxy
    external: true
