---
services:

  n8n:
    image: docker.n8n.io/n8nio/n8n
    container_name: app--n8n
    restart: unless-stopped
    ports:
      - '5678:5678'
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - n8n_data:/home/node/.n8n
    environment:
      - GENERIC_TIMEZONE=Europe/Bucharest
      - TZ=Europe/Bucharest
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=sys--proxy"
      - "traefik.http.routers.n8n.rule=Host(`n8n.example.com`)"
      - "traefik.http.routers.n8n.entrypoints=https"
      - "traefik.http.routers.n8n.tls=true"
      - "traefik.http.routers.n8n.middlewares=internal-whitelist@file"
      - "traefik.http.services.n8n.loadbalancer.server.port=5678"

volumes:
  n8n_data:
    driver: local

networks:
  proxy:
    name: sys--proxy
    external: true
