{
 "title": "Proxmox VE",
 "description": "Proxmox VictoriaMetrics dashboard",
 "tags": [
  "ProxmoxVE",
  "VictoriaMetrics",
  "Qemu",
  "LXC"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "Hypervisor",
    "query": "label_values(system_uptime{object=\"nodes\"}, host)"
   },
   {
    "name": "cores",
    "query": "query_result(cpustat_cpus{host=\"$node\"})"
   },
   {
    "name": "obj_types",
    "query": "query_result(system_uptime{nodename=\"$node\"} > 0)"
   }
  ]
 },
 "panels": [
  { "title": "Main Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Running LXC",
   "type": "table",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "targets": [
    {
     "expr": "max by (host) (system_uptime{nodename=\"$node\", object=\"lxc\"}[$__interval]) > 0"
    }
   ]
  },
  {
   "title": "Running VMs",
   "type": "table",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "targets": [
    {
     "expr": "max by (host) (system_uptime{nodename=\"$node\", object=\"qemu\"}[$__interval]) > 0"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by(host) (system_uptime{object=\"nodes\", host=\"$node\"})"
    }
   ]
  },
  {
   "title": "Active Virtual Machines",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(max by (host) (system_uptime{object!=\"nodes\", nodename=\"$node\"}) > 0)"
    }
   ]
  },
  {
   "title": "Total Cores",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cpustat_cpus{host=\"$node\"}"
    }
   ]
  },
  {
   "title": "Total Memory",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "memory_memtotal{host=\"$node\"}"
    }
   ]
  },
  {
   "title": "Total Swap",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "memory_swaptotal{host=\"$node\"}"
    }
   ]
  },
  { "title": "Hardware load", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none", "label": "Percent" }
   ],
   "targets": [
    {
     "expr": "avg by (host) (cpustat_avg1{host=\"$node\"}[$__interval])",
     "legendFormat": "Load Average (1 Min)"
    },
    {
     "expr": "avg by (host) (cpustat_cpu{host=\"$node\"}[$__interval]) * 100",
     "legendFormat": "CPU Usage"
    },
    {
     "expr": "avg by (host) (cpustat_wait{host=\"$node\"}[$__interval]) * 100",
     "legendFormat": "I/O Wait"
    }
   ]
  },
  {
   "title": "Host Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none", "label": "Percent" }
   ],
   "targets": [
    {
     "expr": "avg by (host) (memory_memused{object=\"nodes\", host=\"$node\"}[$__interval]) / 1024 / 1024 / 1024",
     "legendFormat": "Occupied"
    },
    {
     "expr": "avg by (host) (memory_memused{object=\"nodes\", host=\"$node\"} / memory_memtotal{object=\"nodes\", host=\"$node\"} * 100)",
     "legendFormat": "Memory Usage"
    }
   ]
  },
  {
   "title": "Storages Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "system_used{object=\"storages\", nodename=\"$node\"} / system_total{object=\"storages\", nodename=\"$node\"} * 100",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Network Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "abs(avg by (instance) (rate(nics_receive{object=\"nodes\", host=\"$node\", instance=~\"(bond|vmbr).*\"})[$__interval])) * 8",
     "legendFormat": "{{ instance }} Rx"
    },
    {
     "expr": "abs(avg by (instance) (rate(nics_transmit{object=\"nodes\", host=\"$node\", instance=~\"(bond|vmbr).*\"})[$__interval])) * 8",
     "legendFormat": "{{ instance }} Tx"
    }
   ]
  },
  {
   "title": "$obj_types nodes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "repeat": "obj_types",
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage $obj_types nodes",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "avg by (host) (system_cpu{object=\"$obj_types\", nodename=\"$node\"}[$__interval] != on(host) system_uptime{nodename=\"$node\", object=\"$obj_types\"}[$__interval]) * 100",
       "legendFormat": "{{host}}"
      }
     ]
    },
    {
     "title": "Mem Usage $obj_types nodes",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "avg by (host) (system_mem{nodename=\"$node\", object=\"$obj_types\"}[$__interval] / on(host) system_maxmem{nodename=\"$node\", object=\"$obj_types\"}[$__interval] != on(host) system_uptime{nodename=\"$node\", object=\"$obj_types\"}) * 100",
       "legendFormat": "{{host}}"
      }
     ]
    },
    {
     "title": "I/O Read on $obj_types nodes",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "irate(system_diskread{nodename=\"$node\", object=\"$obj_types\"}[$__interval] != on(host) system_uptime{nodename=\"$node\", object=\"$obj_types\"})[$__interval]",
       "legendFormat": "{{host}}"
      }
     ]
    },
    {
     "title": "I/O Write on $obj_types nodes",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "irate(system_diskwrite{nodename=\"$node\", object=\"$obj_types\"} != on(host) system_uptime{nodename=\"$node\", object=\"$obj_types\"})[$__interval]",
       "legendFormat": "{{host}}"
      }
     ]
    },
    {
     "title": "Rx Traffic on $obj_types",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
     "yaxes": [
      { "format": "bps" }
     ],
     "targets": [
      {
       "expr": "irate(system_netin{nodename=\"$node\", object=\"$obj_types\"}[$__interval] != on(host) system_uptime{nodename=\"$node\", object=\"$obj_types\"})[$__interval] * 8",
       "legendFormat": "{{host}}"
      }
     ]
    },
    {
     "title": "Tx Traffic on $obj_types",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
     "yaxes": [
      { "format": "bps" }
     ],
     "targets": [
      {
       "expr": "irate(system_netout{nodename=\"$node\", object=\"$obj_types\"}[$__interval] != on(host) system_uptime{nodename=\"$node\", object=\"$obj_types\"})[$__interval] * 8",
       "legendFormat": "{{host}}"
      }
     ]
    }
   ]
  }
 ]
}