global:
  scrape_interval: 15s
  evaluation_interval: 15s

remote_write:
  - url: "http://victoriametrics:8428/api/v1/write"
    queue_config:
      max_samples_per_send: 10000
      capacity: 20000
      max_shards: 30
    write_relabel_configs:
      - source_labels: [__name__]
        regex: 'go_.*'
        action: drop

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'local_node'
    static_configs:
      - targets: ['node-exporter:9100']
        labels:
          instance: 'localhost'
    metrics_path: /metrics
    # relabel_configs:
    #   - source_labels: [__address__]
    #     target_label: instance
    #     regex: '(.*):.*'
    #     replacement: $1

  - job_name: 'cadvisor'
    scrape_interval: 5s
    static_configs:
      - targets: ['cadvisor:8080']
        labels:
          instance: 'docker'

  # - job_name: 'host_name'
  #   static_configs:
  #     - targets: ['192.168.0.111:9100']
  #       labels:
  #         instance: 'host_name'

  # - job_name: "hass"
  #   scrape_interval: 60s
  #   metrics_path: /api/prometheus
  #   bearer_token: "your.longlived.token"
  #   scheme: https
  #   static_configs:
  #     - targets: ['HOSTNAME:8123']
