global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'local_node'
    static_configs:
      - targets: ['node-exporter:9100']
    metrics_path: /metrics
    scrape_interval: 5s
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        regex: '(.*):.*'
        replacement: $1

  - job_name: 'cadvisor'
    scrape_interval: 5s
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'hlpve1_node'
    static_configs:
      - targets: ['192.168.189.21:9100']
        labels:
          instance: 'hlpve1'

  - job_name: 'vpn1h1_node'
    static_configs:
      - targets: ['192.168.189.51:9100']
        labels:
          instance: 'vpn1h1'

  - job_name: 'vpn2h2_node'
    static_configs:
      - targets: ['192.168.189.52:9100']
        labels:
          instance: 'vpn2h2'
